version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_convify
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: convify
      MYSQL_USER: convifyuser
      MYSQL_PASSWORD: convifypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
