export const CRAFT_ELEMENTS = {
  USERCONTAINER: "UserContainer",
  LAYOUTCONTAINER: "LayoutContainer",
  CARD: "Card",
  CARDCONTENT: "CardContent",
  CONTAINER: "Container",
  LOGO: "Logo",
  DIV: "div",
  LOGOBAR: "LogoBar",
  LOGOBARITEM: "LogoBarItem",
  PROGRESSBAR: "ProgressBar",
  ICONBUTTON: "IconButton",
  SELECT: "Select",
  USERINPUT: "UserInput",
  USERTEXT: "UserText",
  HEADLINETEXT: "HeadlineText",
  PICTURECHOICE: "PictureChoice",
  MULTIPLECHOICE: "MultipleChoice",
  SCREENFOOTER: "ScreenFooter",
}
