import { TSelectOptions, Template } from "@/types"

export const InsightsDevices: TSelectOptions[] = [
  {
    id: 1,
    value: "All Devices",
    label: "All Devices",
  },
  {
    id: 2,
    value: "Desktop",
    label: "Desktop",
  },
  {
    id: 3,
    value: "Mobile",
    label: "Mobile",
  },
  {
    id: 4,
    value: "Tablet",
    label: "Tablet",
  },
]

export const locales = ["en", "pt"]

export const defaultLocale = "en"

export const templates: Template[] = [
  {
    id: 0,
    name: "B2B SaaS Demo",
    isPopular: false,
    img: "template-0",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 1,
    name: "B2B Lead-Gen Marketing",
    isPopular: true,
    img: "template-1",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 2,
    name: "B2B Webinar",
    isPopular: true,
    img: "template-2",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 3,
    name: "B2B Product Recommendation",
    isPopular: false,
    img: "template-3",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 4,
    name: "B2B Webinar",
    isPopular: false,
    img: "template-4",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 5,
    name: "B2B Cleaning Services",
    isPopular: false,
    img: "template-5",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 6,
    name: "B2B Download Whitepaper",
    isPopular: false,
    img: "template-6",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 7,
    name: "B2B Lead Gen (Dark Mode)",
    isPopular: false,
    img: "template-7",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 8,
    name: "B2B Return on Investment Calculator",
    isPopular: false,
    img: "template-8",
    isRecommended: true,
    category: "B2B Lead-Gen",
  },
  {
    id: 9,
    name: "Social Recruiting",
    isPopular: true,
    category: "Recruiting",
    img: "template-9",
    isRecommended: false,
  },
  {
    id: 10,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-10",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 11,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-11",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 12,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-12",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 10,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-10",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 13,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-13",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 14,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-14",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 15,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-15",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 16,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-16",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 17,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-17",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 18,
    name: "Recruiting - Craft",
    category: "Recruiting",
    img: "template-18",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 19,
    name: "B2C Generic Appointment",
    isPopular: true,
    category: "B2C Lead-Gen",
    img: "template-19",
    isRecommended: false,
  },
  {
    id: 20,
    name: "B2C Real Estate Value",
    isPopular: true,
    category: "B2C Lead-Gen",
    img: "template-20",
    isRecommended: false,
  },
  {
    id: 21,
    name: "B2C Solar Quote",
    category: "B2C Lead-Gen",
    img: "template-21",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 22,
    name: "B2C Dental Insurance",
    category: "B2C Lead-Gen",
    img: "template-22",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 23,
    name: "B2C Dream Kitchen",
    category: "B2C Lead-Gen",
    img: "template-23",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 24,
    name: "B2C Life Insurance",
    category: "B2C Lead-Gen",
    img: "template-24",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 25,
    name: "B2C Mortgage Calculator",
    category: "B2C Lead-Gen",
    img: "template-25",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 26,
    name: "B2C Pet Insurance",
    category: "B2C Lead-Gen",
    img: "template-26",
    isRecommended: true,
    isPopular: false,
  },
  {
    id: 27,
    name: "B2C Test Drive",
    category: "B2C Lead-Gen",
    img: "template-27",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 28,
    name: "B2C Solar Calculator",
    category: "B2C Lead-Gen",
    img: "template-28",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 29,
    name: "B2C Solar Landing Page",
    category: "B2C Lead-Gen",
    img: "template-29",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 30,
    name: "B2C Solar Lead Flow",
    category: "B2C Lead-Gen",
    img: "template-30",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 31,
    name: "Simple Lead Form – Travel",
    category: "B2C Lead-Gen",
    img: "template-31",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 32,
    name: "Marketfit Survey",
    category: "Customer Feedback",
    img: "template-32",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 33,
    name: "NPS Survey",
    category: "Customer Feedback",
    img: "template-33",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 34,
    name: "Employee Satisfaction Survey",
    category: "Others",
    img: "template-34",
    isRecommended: false,
    isPopular: false,
  },
  {
    id: 35,
    name: "Nutrition Flow",
    category: "Others",
    img: "template-35",
    isRecommended: false,
    isPopular: false,
  },
]

export const DefaultImagePlaceholder =
  "https://siteimages.b-cdn.net/flow/default-image.30d08cea.webp"


export const TERMS_URL = 'https://policies.google.com/terms'
export const PRIVACY_URL = "https://policies.google.com/privacy"