import { IconButtonProps } from "./user-icon-button.component";

export const filledPreset:IconButtonProps={
  fontFamily: {
    value: "inherit",
    globalStyled: true,
    isCustomized: false,
  },
  background: {
    value: "#4050ff",
    globalStyled: true,
    isCustomized: false,
  },
  color: {
    value: "#ffffff",
    globalStyled: false,
    isCustomized: true,
  },
  backgroundHover: {
    value: "#3182ce",
    globalStyled: true,
    isCustomized: false,
  },
  colorHover: {
    value: "#ffffff",
    globalStyled: false,
    isCustomized: true,
  },
  radius:{
    value: "0",
    globalStyled: false,
    isCustomized: false,
  },
  borderColor: {
    value: "#00FF00",
    globalStyled: true,
    isCustomized: false,
  },
  borderHoverColor: {
    value: "inherit",
    globalStyled: true,
    isCustomized: false,
  },
  justifyContent: "space-between",
  disabled: false,
  enableIcon: true,
  width: "366",
  height: "auto",
  size: "small",
  text: "Get quote",
  marginLeft: 0,
  marginTop: 0,
  marginRight: 0,
  marginBottom: 0,
  icon: "arrowright",
  paddingLeft: "16",
  paddingTop: "26",
  paddingRight: "16",
  paddingBottom: "26",
  flexDirection: "row",
  alignItems: "center",
  gap: 4,
  border: 0,
};

export const outLinePreset:IconButtonProps={
  fontFamily: {
    value: "inherit",
    globalStyled: true,
    isCustomized: false,
  },
  background: {
    value: "#ffffff",
    globalStyled: false,
    isCustomized: true,
  },
  color: {
    value: "#3182ce",
    globalStyled: true,
    isCustomized: false,
  },
  backgroundHover: {
    value: "#fefefe",
    globalStyled: false,
    isCustomized: true,
  },
  colorHover: {
    value: "#3180ca",
    globalStyled: true,
    isCustomized: false,
  },
  radius:{
    value: "8",
    globalStyled: false,
    isCustomized: false,
  },
  borderColor: {
    value: "#3182ce",
    globalStyled: true,
    isCustomized: false,
  },
  borderHoverColor: {
    value: "#3182ce",
    globalStyled: true,
    isCustomized: false,
  },
  justifyContent: "space-between",
  disabled: false,
  enableIcon: true,
  width: "366",
  height: "auto",
  size: "small",
  text: "Get quote",
  marginLeft: 0,
  marginTop: 0,
  marginRight: 0,
  marginBottom: 0,
  icon: "arrowright",
  paddingLeft: "16",
  paddingTop: "26",
  paddingRight: "16",
  paddingBottom: "26",
  flexDirection: "row",
  alignItems: "center",
  gap: 4,
  border: 2,
};
